[package]
name = "egui-app"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.23.0", features = ["__screenshot"] }
egui_extras = { version = "0.23.0", features = ["image"] }
env_logger = "0.10.0"
egui_dock = "0.8.0"
